stages:
  - downloud
  - test app
  - build
  - test build
  - stop
  - start


downloud:
  stage: downloud
  tags:
    - frontbuilder
  script:
    - sudo curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
    - sudo apt install nodejs -y
    - npm -v
    - node -v
    - sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb  -y

install:
  stage: downloud
  tags:
    - frontbuilder
  script: 
    - sudo npm install pm2@latest -g
    - npm install
  artifacts:
        paths:
          - node_modules/ 

test:
  stage: test app
  tags:
    - frontbuilder
  script: 
    - npm run test:cypress

build:
  stage: build
  tags:
    - frontbuilder
  script: 
    - npm run build
  artifacts:
        paths:
          - build/ 

stop:
  stage: stop
  tags:
    - frontbuilder
  script: 
    - pm2 delete "my-react-app"
  

start:
  stage: start
  tags: 
    - frontbuilder
  script:
    pm2 serve build 8000 --name "my-react-app"
